### ISSUE TITLE
size is not a function attachment.js

### ISSUE THREAD

**Issue by sebastienserre** [shamim2883/front-end-pm#71]
Hello,
An error make multiple attachments unavailable
```TypeError: $(...).size is not a function attachment.js:5:77
    <anonyme> https://projeteurs.thivinfo.dev/wp-content/plugins/front-end-pm/assets/js/attachment.js?ver=11.2.1:5
    jQuery 2
```

**Comment by sebastienserre** [comment]
corrected in #72

**Comment by shamim2883** [comment]
Which jQuery version you are using? This function is removed from jQuery version 3.0, But wordpress is still not using this version. Are you loading jQuery from another location other that wordpress core?

**Comment by sebastienserre** [comment]
Hello @shamim2883 ,
You're right my Front end dev is loading jQuery 3.3.1 in it's theme.
So, what about my PR #72 ?
